services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 3SrmsA+F4KcV2yOTm5cXT8xlzIOJ9irkZmm5hhkjmo8=
      MARIADB_USER: ctf-server
      MARIADB_PASSWORD: Super_Password
      MARIADB_DATABASE: esgi_db
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init_db.sql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - app-network
  app:
    build: .
    environment:
      DB_HOST: db
      TZ: Europe/Paris
    ports:
      - "443:8080"
    depends_on:
      - db
    networks:
      app-network:
      ctf-docker:
        ipv4_address: 192.168.9.100
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
volumes:
  db_data:
networks:
  app-network:
  ctf-docker:
    name: ctf-docker
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.9.0/24 
