services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: I4jVfl9hDBUK+6NMiYAr53cLpCl0Pr/eCc/8ZHQyzD0=
      MARIADB_USER: ctf-server
      MARIADB_PASSWORD: SuperPass
      MARIADB_DATABASE: esgi_db
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - app-network

  app:
    build: .
    environment:
      DB_HOST: db 
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:

