connector-windows:
    children:
      vm_windows:

connector-linux:
    children:
      vm_linux:

all:
    # vars_files:
    #   - ./docker.yml
    vars:
      ctf_id: 1
      ctf: debug
      vm_host_ip: 192.168.56.1
    children:
      vm_linux:
        hosts:
          Crow_10:
            ansible_host: 192.168.56.10
            ip: 192.168.56.10
            machine_name: Crow
            flag_location: /root
          Crow_11:
            ansible_host: 192.168.56.11
            ip: 192.168.56.11
            machine_name: Crow
            flag_location: /root
          Crow_12:
            ansible_host: 192.168.56.12
            ip: 192.168.56.12
            machine_name: Crow
            flag_location: /root
          Cat_13:
            ansible_host: 192.168.56.13
            ip: 192.168.56.13
            machine_name: cat
            flag_location: /root
          Cat_14:
            ansible_host: 192.168.56.14
            ip: 192.168.56.14
            machine_name: cat
            flag_location: /root
          Clip_15:
            ansible_host: 192.168.56.15
            ip: 192.168.56.15
            machine_name: Clip
            flag_location: /root
          Fast_16:
            ansible_host: 192.168.56.16
            ip: 192.168.56.16
            machine_name: Fast
            flag_location: /root
          Fast_17:
            ansible_host: 192.168.56.17
            ip: 192.168.56.17
            machine_name: Fast
            flag_location: /root
          Run_18:
            ansible_host: 192.168.56.18
            ip: 192.168.56.18
            machine_name: Run
            flag_location: /root
          Run_19:
            ansible_host: 192.168.56.19
            ip: 192.168.56.19
            machine_name: Run
            flag_location: /root
          Run_20:
            ansible_host: 192.168.56.20
            ip: 192.168.56.20
            machine_name: Run
            flag_location: /root
          Clock_21:
            ansible_host: 192.168.56.21
            ip: 192.168.56.21
            machine_name: Clock
            flag_location: /root
          Clock_22:
            ansible_host: 192.168.56.22
            ip: 192.168.56.22
            machine_name: Clock
            flag_location: /root
          Clock_23:
            ansible_host: 192.168.56.23
            ip: 192.168.56.23
            machine_name: Clock
            flag_location: /root
          Rovigo_24:
            ansible_host: 192.168.56.24
            ip: 192.168.56.24
            machine_name: Rovigo
            flag_location: /root
          Rovigo_25:
            ansible_host: 192.168.56.25
            ip: 192.168.56.25
            machine_name: Rovigo
            flag_location: /root
          Rovigo_26:
            ansible_host: 192.168.56.26
            ip: 192.168.56.26
            machine_name: Rovigo
            flag_location: /root
