all:
  hosts:
    Crow0:
      ansible_host: 192.168.56.20
      ansible_user: prof
      ansible_ssh_pass: password
      # ansible_user: ansible_user # Uncomment after first playbook run
      # ansible_become: yes # Décommentez si vous avez besoin d'une élévation de privilèges
      # ansible_become_pass: mot_de_passe_initial # Décommentez si sudo nécessite un mot de passe
