- name: Retrieve ansible password from secrets/ansible_passwd
  delegate_to: localhost
  become: no
  slurp:
    src: ../secrets/ansible_passwd  # Relative path from the playbook location
  register: slurped_password

- name: Decode the ansible password
  set_fact:
    ansible_passwd: "{{ slurped_password.content | b64decode }}"

- name: debug
  debug:
    var: ansible_passwd

- name: Hash the ansible password
  set_fact:
    ansible_passwd_hash: "{{ ansible_passwd | password_hash('sha512') }}"


- name: Debug ansible_passwd_hash
  debug:
    msg: "Hashed password is {{ ansible_passwd_hash }}"

- name: Create Ansible user
  user:
    name: "{{ ansible_user_name }}"
    password: "{{ ansible_passwd_hash }}"
    shell: /bin/bash
    update_password: always
    create_home: yes

- name: Provides sudo access to the Ansible user
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^{{ ansible_user_name }}"
    line: "{{ ansible_user_name }} ALL=(ALL) NOPASSWD: ALL"
    validate: visudo -cf %s

- name: Add the public key to the authorized_keys file
  authorized_key:
    user: "{{ ansible_user_name }}"
    state: present
    key: "{{ lookup('file', '../../secrets/ctf.pub') }}"

- name: Set correct rights on the authorized_keys file
  file:
    path: "/home/{{ ansible_user_name }}/.ssh/authorized_keys"
    owner: "{{ ansible_user_name }}"
    group: "{{ ansible_user_name }}"
    mode: '0644'

- name: Enable the key-based authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PubkeyAuthentication"
    line: "PubkeyAuthentication yes"
    state: present
  notify: restart sshd

- name: Redémarrer le service SSH pour appliquer les modifications
  service:
    name: ssh
    state: restarted
  when: ansible_service_mgr is defined
