- name: Configurer le nouvel utilisateur et les paramètres de sécurité
  hosts: all
  gather_facts: no
  serial: 1
  roles:
    - roles/ctf_enroll
    - role: roles/vm_cleanup
      when: "'vm_linux' in group_names"