---
- name: Copy files to remote host
  copy:
    src: "../../../vm_client/{{ item }}"
    dest: "{{ flag_location }}"
    owner: "root"
    group: "root"
    mode: '0744'
  loop:
    - "flag.sh"
    - "flag.conf"
    - "cert.pem"
    - "network.sh"
  become: yes
  when: "'vm_linux' in group_names"

- name: Install winrm
  delegate_to: localhost
  ansible.builtin.pip:
    name: pywinrm
  when: "'vm_windows' in group_names"
  become: no

- name: Copy files to Windows hosts
  copy:
    src: "../../../vm_client/{{ item }}"
    dest: "{{ flag_location }}"
    owner: "Administrator"
  loop:
    - "flag.ps1"
    - "flag.conf"
    - "cert.der"
  become: yes
  become_method: runas
  become_user: Administrator
  when: "'vm_windows' in group_names"