- name: Log out the instance
  command: 
    cmd: "{{ flag_location }}/flag.sh -l"
    chdir: "{{ flag_location }}"
  become: yes

# - name: Shutdown the instance
#   command: 
#     cmd: "shutdown 0"
#   become: yes
