- name: Linux - Log out the instance
  command: 
    cmd: "{{ flag_location }}/flag.sh -l"
    chdir: "{{ flag_location }}"
  become: yes
  when: "'vm_linux' in group_names"

- name: Windows - Log out the instance
  ansible.windows.win_shell: |
    Set-Location "{{ flag_location }}"
    ./flag.ps1 -l
  become: true
  become_method: runas
  become_user: Administrator
  when: "'vm_windows' in group_names"

# - name: Shutdown the instance
#   command: 
#     cmd: "shutdown 0"
#   become: yes
